export const PLUGIN_ID = "ktsang.issue-templates";

export type TemplateEntry = {
  key: string;
  label: string;
  template: string;
};

export const DEFAULT_TEMPLATE_ENTRIES: TemplateEntry[] = [
  {
    key: "bug",
    label: "Bug",
    template: [
      "**What happened**",
      "*What is broken? Describe the actual behavior in one or two sentences.*",
      "",
      "",
      "**Impact**",
      "*Who is affected, how often, and how severe is it?*",
      "",
      "",
      "**Steps to reproduce**",
      "1. ",
      "2. ",
      "3. ",
      "",
      "**Expected behavior**",
      "*What should have happened instead?*",
      "",
      "",
      "**Evidence**",
      "*Include stack trace, logs, screenshots, links, or exact error text.*",
      "",
      "",
      "**Environment**",
      "App/repo: ",
      "Version/branch: ",
      "Environment: local / staging / production",
      "Device/browser (if relevant): ",
      "",
      "**Workaround**",
      '*Is there a temporary workaround? If none, say "none".*',
      "",
      "",
      "**Done when**",
      "*What outcome would count as fixed?*",
      "",
      "",
    ].join("\n"),
  },
  {
    key: "task",
    label: "Task",
    template: [
      "**What needs to happen**",
      "*Describe the required change clearly and directly.*",
      "",
      "",
      "**Why**",
      "*Why does this matter now?*",
      "",
      "",
      "**Done when**",
      "- [ ] ",
      "",
      "**Scope**",
      "*What repo/service/file area is in scope? What is explicitly out of scope?*",
      "",
      "",
      "**Dependencies or blockers**",
      "*Anything this task depends on, or anything that could block it?*",
      "",
      "",
      "**Context**",
      "*Relevant background, links, screenshots, notes, or prior decisions.*",
      "",
      "",
    ].join("\n"),
  },
  {
    key: "investigation",
    label: "Investigation",
    template: [
      "**Question**",
      "*What needs to be understood or explained?*",
      "",
      "",
      "**Why now**",
      "*Why is this worth investigating now? Is there a deadline or trigger?*",
      "",
      "",
      "**What we already know**",
      "*Facts, observations, logs, prior fixes, or failed attempts.*",
      "",
      "",
      "**Hypothesis**",
      '*If you have a leading theory, write it here. Otherwise say "unknown".*',
      "",
      "",
      "**Evidence**",
      "*Logs, stack traces, screenshots, links, metrics, or examples.*",
      "",
      "",
      "**Done when**",
      "*What output is expected: root cause, recommendation, options, repro, etc.?*",
      "",
      "",
    ].join("\n"),
  },
  {
    key: "enhancement",
    label: "Enhancement",
    template: [
      "**What should change**",
      "*Describe the desired improvement.*",
      "",
      "",
      "**Current behavior**",
      "*What happens today?*",
      "",
      "",
      "**Desired behavior**",
      "*What should happen after the change?*",
      "",
      "",
      "**Who benefits**",
      "*Who is this for, and why does it matter?*",
      "",
      "",
      "**Alternatives considered**",
      "*Any rejected or possible alternatives.*",
      "",
      "",
      "**Constraints**",
      "*Anything to preserve, avoid, or keep compatible.*",
      "",
      "",
      "**Done when**",
      "*How will we know this enhancement is complete?*",
      "",
      "",
    ].join("\n"),
  },
];

/** Default keys for identifying built-in types. */
export const DEFAULT_KEYS = new Set(DEFAULT_TEMPLATE_ENTRIES.map((e) => e.key));
